services:
  db:
    image: mysql
    container_name: riskreal-db-1
    restart: always
    environment:
      MYSQL_DATABASE: appRiskRealUbu
      MYSQL_ROOT_PASSWORD: rootroot
    expose:
      - '3306'
    ports:
      - '30306:3306'
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - riskreal-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  webapp:
    image: ghcr.io/daniel-fernandez-ubu/riskrealubu/riskrealapp
    container_name: riskreal-webapp-1
    environment:
      JSON_QUIZ_FILE_PATH: /opt/jsonFiles
      JSON_QUIZ_FILE_PATH_LANG: /opt/jsonFiles/lang
      CSV_SCORE_PATH: /opt/csvFiles/scores.csv
      JSON_QUIZ_IMAGES_PATH: ../images/
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/appRiskRealUbu
      SPRING_DATASOURCE_PASSWORD: rootroot
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SERVER_PORT: 8088
      ADMIN_USERNAME: admin@riskreal.com
      ADMIN_PASSWORD: admin
      TEST_QUIZ: test_quiz_
    ports:
      - '8088:8088'
    volumes:
      - ./appFiles:/opt

    networks:
      - riskreal-network
    depends_on:
      db:
        condition: service_healthy

networks:
  riskreal-network:

